#!/bin/bash
# Unpacks a mission from the last DCS track
# Usage: unpack-last-trk <directory>, for example:
# unpack-last-trk "/c/Users/Username/DCS/Saved Games/Tracks/Multiplayer"
TRK_DIR=$1
TRK_FILE=$(ls -dtr "${TRK_DIR}"/* | tail -n 1)
DEST_DIR=$(basename "${TRK_FILE}" | cut -d- -f1)-$(basename "${TRK_FILE}" | cut -d- -f2)
mkdir "${DEST_DIR}"
cd "${DEST_DIR}"
unzip "${TRK_FILE}" l10n/** mission options theatre warehouses
